### PR TITLE
Added support for LG Devices Running KitKat. Fixed two little bugs....

### PR DESCRIPTION
**Pull request by P-Toti**
Added support for almost all LG Devices Running KitKat.(I checked the code of G2,G-Flex,G-Pro,G-Pro 2,G-Pad only but It will probably work on all LG devices running KitKat)
Fixed a little bug: 
Unlinking Status And Navigation Bar color setting only for some apps was ignored

### CODE REVIEW

**Comment by GermainZ** [comment]
A small note: 1) is already fixed.

**Comment by P-Toti** [comment]
Yeah sorry, i just noticed that . I updated the forked now :)

**Comment by P-Toti** [comment]
LG Hooks have been reworked and commit to fix the bug already fixed by GermainZ has been removed.

**Comment by MohammadAG** [comment]
I've changed a lot of the coding style to match TSB's. I've also added a check so that this doesn't run on devices other than those manufactured by LG.

Also, what does com.lge.systemui.StatusBarBackground extend?

I'd appreciate it if you could test it again with these changes.

**Comment by P-Toti** [comment]
Good job :) . I didn't use a manufacturer check because the class can be found on lg devices only and the exception is caught. The StatusBarBackground extends an ImageView . There are several reasons why i chosen to hook it. I will test all changes tonight but basically it is the exact code so it should not be any problem. I have found another bug : if i use the gradient over tint and the status and navigation bar color is linked i will always have a white navigation bar icons (lines 385-387 of ColourChangerMod.java). Also in this way if i want to intercept the intent to color an icon injected by my mod i will always fail because the color is different and there is not any extra that says the fake gradient is enabled.

**Comment by MohammadAG** [comment]
Can you check if this works then?
https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/commit/10988d4f483de2b6e52c79c5dd0287e811ab2ccf

If it extends ImageView, we should be using the methods without reflection :)

The bug you mentioned should be fixed with https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/commit/e4a5dae598ce750e71e3b08fc2a0e3aa3a048505

Wouldn't have noticed it since I don't use linked bars, so thanks!

**Comment by P-Toti** [comment]
You are very welcome, yeah i don't see any reason why it should not work but i will check as requested. About the bug with e4a5dae it should be fixed but the color in the intent and the one actually used mismatches so i think you should add an extra to the intent so we can know the fake gradient is enabled and use the fixed color.

**Comment by P-Toti** [comment]
I checked 10988d4 and e4a5dae . Both are working fine as expected :+1:

**Pull request merged**
