### PR TITLE
Updated LG Support and italian translation

### PR DESCRIPTION
**Pull request by P-Toti**
Italian translation updated. Added LG G3 Support(users confirmed to be working). Hooked the setImeWindowStatus method to make keyboard options working on LG devices. I paid attention to the style this time, i hope it's fine now if not please excuse me.

### CODE REVIEW

**Comment by MohammadAG** [comment]
keyboard_up shouldn't be an extra that's related to LG devices, instead, pass ColourChangerMod instance in the constructor and use the method onKeyboardVisible(boolean visible)

Also, doImeHooks should be in doHooks rather than being called separately.

**Comment by P-Toti** [comment]
That method is not in the Systemui that's why it's called separately. Also,how can passing the instance and calling that method work ? It should not work because the navigationbarview should be null when onKeyboardVisible is called  from the hooked method. Btw maybe i wrong so i will test and report back. Thanks for your answer

**Comment by P-Toti** [comment]
Tried but as i though it's not working.

**Comment by MohammadAG** [comment]
Oh, I missed that it was in Zygote, sorry.

I've added a new intent for keyboard visibility, merged! :)

**Comment by P-Toti** [comment]
Good work :)

**Pull request merged**
